name: Check Labels
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - reopened
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"
