name: Check Labels
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - reopened
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        run: |
          ls -laR
          chmod +x "${GITHUB_WORKSPACE}/.github/check-labels.sh"
          .github/check-labels.sh
        env:
          LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
