name: Translation Guard
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - reopened
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - run: |
        chmod +x ".github/check-labels.sh"
        .github/check-labels.sh
      env:
        LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
