name: Lint
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - "docs/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      # Inconvenient way to bypass the heavy installation of VuePress.
      - run: npm i --ignore-scripts eslint eslint-config-airbnb-base eslint-plugin-import markdownlint-cli2
      - run: npm run docs:lint
